### ISSUE TITLE
Loading different pointclouds

### ISSUE THREAD

**Issue by KatherineJames** [jasonkena/L1-Skeleton#3]
Hi @jasonkena 

Firstly thanks for your efforts in docker-ising this - super helpful! I was hoping you could tell me how to load point clouds other than the default ones - when I try the import ply/skel I cannot see any of my own ply that I have placed in the project...and if I try and drag them in then I get the message 'failed reading mesh' error. Is there only a very specific format that this can handle? Any additional information here would be super helpful, thank you.

**Comment by jasonkena** [comment]
Heya @KatherineJames, I found success by using the PLY files generated by the Open3D, see https://github.com/jasonkena/L1-Skeleton/blob/0139522a6ee5ea7324201ce12370d116c2462fa0/l1_skeleton.py#L154

Let me know if you need more help.

**Comment by KatherineJames** [comment]
Hi @jasonkena,

Thanks for your reply. My pointclouds are already generated by Open3D - ply and in ascii. My question is more about how to load the ply so that I can skeletonise it. The GUI doesn't pick up on the existence of the ply, and if I drag it in, it gives me an error. Is there another step I am missing/way of doing this?

**Comment by jasonkena** [comment]
![1679500721](https://user-images.githubusercontent.com/35003073/226964789-48571c60-4648-4cfb-a56f-67a7a89923c2.png)
You can just choose the file in the file explorer after you click "Import Ply/Skel", no?

**Comment by KatherineJames** [comment]
No unfortunately not - the file does not show up. Only the default two.

**Comment by jasonkena** [comment]
How are you running the `./PointCloudL1` binary? Are you compiling it locally or are you running it through the Docker container (forwarding the X server, etc.)?

If you run it locally, I think the file explorer allows you to choose a local directory.
![1679502271](https://user-images.githubusercontent.com/35003073/226971833-a0bd8a32-f4d9-4e07-8250-7dd0fb5f4976.png)

If you are running the Docker container, you might need to setup bindmounts to view local directories from inside the container.

**Comment by KatherineJames** [comment]
I'm running it through Docker - so that is probably the issue. I couldn't get all the dependencies working to build it from scratch. Thank you for the input - I'll post on here if I manage to sort it out.

**Comment by KatherineJames** [comment]
Found the solution to my issue in the end - needed to mount my own ply files with -v command so they showed up in the docker.

sudo docker run -it -v $XAUTH:/root/.Xauthority -v /home/path/on/host/myfile.ply:/home/L1-Skeleton/myfile.ply -e DISPLAY=unix$DISPLAY -e LIBGL_ALWAYS_SOFTWARE=1 --net=host --gpus=all pointcloudl1
